### ISSUE TITLE
Hitbox bug

### ISSUE THREAD

**Issue by wetstreet** [skligys/cardboard-creeper#3]
When I turned off auto-jump, I found that collision doesn't work with knee block. When I look into the code, I found that the hitbox of steve is the head block and the block under knee block(the block steve is standing on), that is because of precision of float. At first the y of steve is generated based on block.y + 0.5 +1.62, but it turned out to be a little less than what it should be due to the precision limit, then in the computation of hitbox, minY which is steve.y - 0.5 -1.62 becomes the block under the knee block.

Solution: add a compensation value to the minY

If you want I can make a pull request

**Comment by skligys** [comment]
Sure, PRs welcome.  Sorry about the delay, I was not expecting anybody to even look at this project.

**Comment by wetstreet** [comment]
Never mind. Actually I've got a question though. Is it okay that I used some of your code in my project with reference? I don't know if I'm allowed to do so...I'm not quite familiar with those licences.

**Comment by skligys** [comment]
As the description says here:

https://github.com/skligys/cardboard-creeper/blob/master/LICENSE

you can do whatever you want with source code from this project as long as you include the original copyright and license notice in any copy of the software/source.  This includes commercial and for profit use.

**Comment by wetstreet** [comment]
Got it! Thank you!
